spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/security_jwt
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
jwt:
  secret:
    key: b2e7c6e1f29f13e0d8a6b5c3e07a8b9c6a3f9c8b27f93eac5641d3c72a9a6b0c

